# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
gem "selenium"
gem "selenium-webdriver"
gem "capybara"
gem "cucumber"
gem "rspec"
